### ISSUE TITLE
beasy not in beast package manager

### ISSUE THREAD

**Issue by zenalapp** [rbouckaert/beasy#1]
Hi, 

I have BEASTv2.5.2 installed and would like to try to use beasy to generate my xml files; however, I can't find beasy in the list of available packages in the package manager. Is this package available for use yet?

Thanks!
Zena

**Comment by rbouckaert** [comment]
Hi Zena,

Beasy is still quite experimental -- I put up a release [here](https://github.com/rbouckaert/beasy/releases/tag/v0.0.1), but only if you feel sufficiently comfortable to install it by hand should you attempt to use it. Let me know if you run into trouble.

Remco

**Comment by zenalapp** [comment]
Great, thanks!
